import React from "react";
import Head from "next/head";
import Image from "next/image";

const Home: React.FC = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <p className="font-bold text-2xl text-blue-600">Hello</p>
    </div>
  );
};

export default Home;
